name: MacOS Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14 
    env: 
      DASH_HOME: "/usr/local/dash"
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'
    
    - name: Install LLVM
      run: |
        brew install llvm@18
        echo "/opt/homebrew/opt/llvm@18/bin" >> $GITHUB_PATH    

    - name: Verify LLVM 18
      run: | 
        if llvm-config --version | grep -qE "^18\."; then
          echo "llvm installation verified"
        else
          echo "llvm not properly installed"
          exit 1
        fi

    - name: Install Lua 
      run: brew install lua
         
    - name: Verify Lua
      run: lua -v

    - name: Install Dash
      run: |
        if [ -z "${{ github.event.release.tag_name }}" ]; then
          export DASH_VERSION=$(git rev-parse --short "$GITHUB_SHA")
        else
          export DASH_VERSION="${{ github.event.release.tag_name }}"
        fi
    
        chmod +x scripts/macos/install_macos.sh
        ./scripts/macos/install_macos.sh
        
    - name: Verify Dash
      run: dash version
      
    - name: Test
      run: make test
